### ISSUE TITLE
Fresh Ubuntu 22.04 / not working anymore

### ISSUE THREAD

**Issue by ikorbln** [dontobi/SpeedFlux.rpi#31]
Hi,
I loaded my odroid arm system with fresh Ubuntu 22.04, installed Docker and Portainer.
All is working goos. But the speedflux is not working anymore.
In Portainer i get this in the logs:

Speedtest CLI data logger to InfluxDB started...
Traceback (most recent call last):
  File "/app/main.py", line 177, in <module>
    main()
  File "/app/main.py", line 162, in main
    if pPing.is_alive():
       ^^^^^
UnboundLocalError: cannot access local variable 'pPing' where it is not associated with a value

**Comment by dontobi** [comment]
What version of the container are you using?

**Comment by ikorbln** [comment]
i pulled the latest version v1.3

**Comment by ikorbln** [comment]
A colleague from me looked over it, in the main.py there is missing the complete def pingtest and the pPing part in at the def_main section.

**Comment by dontobi** [comment]
I'll take a look at it and try to fix it. Can you test version 1.2 in the meantime?

**Comment by ikorbln** [comment]
For me it is good now, but you have to add this section befor the def main:

```
def pingtest():
    timestamp = datetime.datetime.utcnow()
    for target in PING_TARGETS.split(','):
        target = target.strip()
        pingtest = ping(target, verbose=False, timeout=1, count=1, size=128)
        data = [
            {
                'measurement': 'pings',
                'time': timestamp,
                'tags': {
                    'namespace': NAMESPACE,
                    'target' : target
                },
                'fields': {
                    'success' : int(pingtest._responses[0].error_message is None),
                    'rtt': float(0 if pingtest._responses[0].error_message is not None else pingtest.rtt_avg_ms)
                }
            }
        ]
        if influxdb_client.write_points(data) == True:
            print("Ping data written to DB successfully")
        else:  # Speedtest failed.
            print("Ping Failed.")

```
And in the def main this one line (the pPing line):

```
def main():
    pSpeed = Process(target=speedtest)
    pPing = Process(target=pingtest)
    init_db()
    loopcount = 0
```

**Comment by dontobi** [comment]
Please test the latest version or download the v1.3 build again. I have just reverted some changes.

**Comment by ikorbln** [comment]
It is working again, thx for update :-)
